
SRCDIR = ..

LIBSTATIC = libxnd-0.2.0b1.lib
LIBSHARED = libxnd-0.2.0b1.dll.lib
!ifndef LIBNDTYPESDIR
LIBNDTYPESDIR = ..\..\ndtypes\libndtypes
!else
LIBNDTYPESDIR = "$(LIBNDTYPESDIR)"
!endif
LIBNDTYPESIMPORT = $(LIBNDTYPESDIR)\libndtypes-0.2.0b1.dll.lib


CC = cl.exe
CFLAGS = /nologo /MT /Ox /GS /EHsc
CFLAGS_SHARED = /nologo /DIMPORT /MD /Ox /GS /EHsc

default: runtest runtest_shared


runtest:\
Makefile runtest.c test_fixed.c test.h $(SRCDIR)\xnd.h $(SRCDIR)\$(LIBSTATIC)
	$(CC) -I$(SRCDIR) -I$(LIBNDTYPESDIR) $(CFLAGS) /Feruntest runtest.c \
	test_fixed.c $(SRCDIR)\$(LIBSTATIC) $(LIBNDTYPESDIR)\libndtypes-0.2.0b1.lib

runtest_shared:\
Makefile runtest.c test_fixed.c test.h $(SRCDIR)\xnd.h $(SRCDIR)\$(LIBSHARED)
	$(CC) -I$(SRCDIR) -I$(LIBNDTYPESDIR) $(CFLAGS_SHARED) /Feruntest_shared \
	runtest.c test_fixed.c $(SRCDIR)\$(LIBSHARED) $(LIBNDTYPESIMPORT)


FORCE:

clean: FORCE
	del /q /f *.exe *.obj *.lib *.dll *.exp *.manifest 2>NUL

distclean: clean
	del /q /f Makefile 2>NUL


