package:
  name: libxnd
  version: 0.2.0b2

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY', 'NA') }}_{{ environ.get('GIT_BUID_STR', 'NA') }}

test:
  skip: True  # tests are in build.sh

requirements:
  build:
    - libndtypes ==0.2.0b2
  run:
    - libndtypes ==0.2.0b2

about:
  home: https://github.com/plures/
  license: BSD 3-clause

source:
  git_url: ../../
